package com.warped.data.local.db

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

val MIGRATION_4_5 = object : Migration(4, 5) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE messages ADD COLUMN images TEXT")
    }
}

val MIGRATION_5_6 = object : Migration(5, 6) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE messages ADD COLUMN stats TEXT")
    }
}

val MIGRATION_6_7 = object : Migration(6, 7) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE local_models ADD COLUMN model_format TEXT NOT NULL DEFAULT 'LITERTLM'")
    }
}

val MIGRATION_7_8 = object : Migration(7, 8) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("""
            CREATE TABLE IF NOT EXISTS download_checkpoints (
                model_id TEXT NOT NULL PRIMARY KEY,
                file_name TEXT NOT NULL,
                file_url TEXT NOT NULL,
                total_bytes INTEGER NOT NULL DEFAULT 0,
                downloaded_bytes INTEGER NOT NULL DEFAULT 0
            )
        """.trimIndent())
    }
}

val MIGRATION_8_9 = object : Migration(8, 9) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE presets ADD COLUMN model_format TEXT NOT NULL DEFAULT 'LITERTLM'")
    }
}

val MIGRATION_9_10 = object : Migration(9, 10) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE messages ADD COLUMN reasoning TEXT")
    }
}

val MIGRATION_10_11 = object : Migration(10, 11) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE local_models ADD COLUMN param_temperature REAL NOT NULL DEFAULT 0.7")
        db.execSQL("ALTER TABLE local_models ADD COLUMN param_top_p REAL NOT NULL DEFAULT 0.9")
        db.execSQL("ALTER TABLE local_models ADD COLUMN param_top_k INTEGER NOT NULL DEFAULT 40")
        db.execSQL("ALTER TABLE local_models ADD COLUMN param_repeat_penalty REAL NOT NULL DEFAULT 1.1")
        db.execSQL("ALTER TABLE local_models ADD COLUMN param_max_tokens INTEGER NOT NULL DEFAULT 2048")
        db.execSQL("ALTER TABLE local_models ADD COLUMN param_context_size INTEGER NOT NULL DEFAULT 4096")
        db.execSQL("ALTER TABLE local_models ADD COLUMN param_seed INTEGER NOT NULL DEFAULT -1")
    }
}

// PERF-09: composite index on messages(conversation_id, created_at) is
// handled by the auto-migration v12 -> v13 generated by Room from the
// schema diff.
