name: Test Trigger

on:
  push:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: echo "Workflow triggered successfully!"
